import React, { createContext, useContext, useState } from 'react';
import { liveTranslatorEngine, lookupFastTranslation } from '../services/liveTranslator';
import { api } from '../services/api';

const TRANSLATIONS = {
  en: {
    app_title: "Sufala AI",
    tagline: "Geospatial Remote Sensing, Soil Health & National Crop Intelligence",
    nav_command_center: "Command Center",
    nav_satellite_srm: "GeoSR-AI Studio",
    nav_soil_precision: "Soil & Depletion",
    nav_national_analytics: "National Analytics",
    nav_ai_agronomist: "AI Agronomist",
    nav_farms: "My Farms",
    nav_weather: "Weather Radar",
    
    // Command Center
    cmd_welcome: "National Agricultural Command Center",
    cmd_sub: "Real-time synergy across Satellite Remote Sensing, Precision Soil Dynamics & Macro-Economic BI",
    cmd_active_farms: "Monitored Farm Land",
    cmd_avg_soil_health: "Avg Soil Health Index",
    cmd_satellite_ready: "SRM AI Neural Engine",
    cmd_national_output: "National Foodgrain Output",
    cmd_quick_actions: "Fast Action Launcher",
    cmd_launch_srm: "Run Satellite Super-Resolution",
    cmd_test_soil: "Simulate Soil NPK Depletion",
    cmd_view_bi: "Open Power BI Analytics",
    cmd_ask_ai: "Ask AI Agronomist (Krishi Mitra)",
    
    // GeoSR-AI
    srm_title: "GeoSR-AI: Satellite Imagery Super-Resolution Studio",
    srm_subtitle: "Deep Learning Based Super Resolution Mapping (SRM) from Medium-Resolution Satellite Imagery (Sentinel-2 & Landsat)",
    srm_select_scene: "Select Satellite Agro-Scene",
    srm_or_upload: "Or Upload Custom Multi-Spectral / RGB Tile",
    srm_model_select: "Neural Architecture",
    srm_scale_factor: "Scaling Factor (GSD Multiplier)",
    srm_run_btn: "Execute Super-Resolution Mapping",
    srm_running: "Processing Tiled Neural Upscaling...",
    srm_view_layers: "Visualization Layers",
    srm_layer_rgb: "Super-Resolved RGB",
    srm_layer_ndvi: "NDVI Canopy Health",
    srm_layer_nir: "False-Color NIR (CIR)",
    srm_layer_unc: "MC Uncertainty Heatmap",
    srm_metrics_header: "Remote Sensing Benchmarks",
    
    // Soil
    soil_title: "Precision Agronomy & 3-Season Soil NPK Depletion",
    soil_subtitle: "Continuous mono-cropping depletion forecasting and restorative crop rotation simulation",
    soil_input_card: "Soil Health Card Parameters",
    soil_nitrogen: "Available Nitrogen (N)",
    soil_phosphorus: "Available Phosphorus (P)",
    soil_potassium: "Available Potassium (K)",
    soil_ph: "Soil Reaction (pH)",
    soil_oc: "Organic Carbon (OC %)",
    soil_calculate: "Compute Soil Health & 3-Season Drawdown",
    soil_depletion_chart: "3-Season Nutrient Trajectory (Monoculture vs Smart Rotation)",
    soil_rotation_rec: "AI Crop Rotation & Restoration Plan",
    
    // National Analytics
    bi_title: "Bharat Agri-Analytics: National Crop & Economic Intelligence",
    bi_subtitle: "Interactive Power BI Re-Engineered Analytics for Crop Production, Farmer Economics, Climate & Soil Matrix",
    bi_tab_crop_prod: "Crop Production & Districts",
    bi_tab_farmer_econ: "Farmer Economics & Land",
    bi_tab_climate_impact: "Monsoon & Climate Effect",
    bi_tab_soil_radar: "Soil Health Radar Matrix",
    bi_filter_state: "Filter State",
    bi_filter_season: "Filter Season",
    bi_total_prod: "Total Production",
    bi_cultivated_area: "Cultivated Area",
    bi_avg_yield: "National Avg Yield",
    bi_avg_income: "Avg Farmer Income",
    
    // AI Chat
    chat_title: "Krishi Mitra — AI Agronomist & RAG Knowledge Engine",
    chat_subtitle: "Instant multilingual scientific advisories powered by ICAR guidelines & agronomy knowledge base",
    chat_placeholder: "Ask about crop diseases, yellowing leaves, fertilizer dosing, PM-KISAN, or soil management...",
    chat_send: "Ask Krishi Mitra",
    
    // General
    status_online: "AI Engine Online",
    status_cpu: "Device: PyTorch CPU/CUDA",
    current_farm: "Active Field",
    view_details: "View Analysis",
    all_states: "All India (National)"
  },
  hi: {
    app_title: "एग्रीस्फेयर एआई (AgriSphere AI)",
    tagline: "भू-स्थानिक उपग्रह रिमोट सेंसिंग, मृदा स्वास्थ्य एवं राष्ट्रीय फसल विश्लेषण",
    nav_command_center: "कमांड सेंटर",
    nav_satellite_srm: "जियोएसआर उपग्रह स्टूडियो",
    nav_soil_precision: "मृदा स्वास्थ्य एवं पोषक तत्व",
    nav_national_analytics: "राष्ट्रीय फसल विश्लेषण",
    nav_ai_agronomist: "कृषि मित्र एआई",
    nav_farms: "मेरे खेत",
    nav_weather: "मौसम रडार",
    
    cmd_welcome: "राष्ट्रीय कृषि कमांड सेंटर",
    cmd_sub: "उपग्रह रिमोट सेंसिंग, सटीक मृदा स्वास्थ्य एवं आर्थिक विश्लेषण का एकीकृत मंच",
    cmd_active_farms: "निगरानी अधीन कृषि भूमि",
    cmd_avg_soil_health: "औसत मृदा स्वास्थ्य सूचकांक",
    cmd_satellite_ready: "उपग्रह न्यूरल इंजन",
    cmd_national_output: "राष्ट्रीय खाद्यान्न उत्पादन",
    cmd_quick_actions: "त्वरित कार्य",
    cmd_launch_srm: "उपग्रह सुपर-रेजोल्यूशन चलाएं",
    cmd_test_soil: "मृदा पोषक तत्व क्षरण जांचें",
    cmd_view_bi: "राष्ट्रीय विश्लेषण डैशबोर्ड खोलें",
    cmd_ask_ai: "कृषि मित्र से पूछें",
    
    srm_title: "जियोएसआर उपग्रह सुपर-रेजोल्यूशन स्टूडियो",
    srm_subtitle: "मध्यम-रेजोल्यूशन उपग्रह चित्रों (Sentinel-2 एवं Landsat) का एआई सुपर-रेजोल्यूशन मैपिंग",
    srm_select_scene: "उपग्रह कृषि दृश्य चुनें",
    srm_or_upload: "या अपनी छवि अपलोड करें",
    srm_model_select: "न्यूरल नेटवर्क मॉडल",
    srm_scale_factor: "स्केलिंग कारक (4x)",
    srm_run_btn: "सुपर-रेजोल्यूशन निष्पादित करें",
    srm_running: "प्रोसेसिंग जारी है...",
    srm_view_layers: "दृश्य परतें",
    srm_layer_rgb: "हाई-रेजोल्यूशन आरजीबी",
    srm_layer_ndvi: "एनडीवीआई फसल स्वास्थ्य",
    srm_layer_nir: "फॉल्स-कलर एनआईआर",
    srm_layer_unc: "अनिश्चितता हीटमैप",
    srm_metrics_header: "गुणवत्ता मानक एवं मेट्रिक्स",
    
    soil_title: "सटीक कृषि एवं 3-सीजन मृदा पोषक तत्व क्षरण",
    soil_subtitle: "एकल-फसल क्षरण पूर्वानुमान एवं फसल चक्र बहाली सिमुलेशन",
    soil_input_card: "मृदा स्वास्थ्य कार्ड इनपुट",
    soil_nitrogen: "उपलब्ध नाइट्रोजन (N)",
    soil_phosphorus: "उपलब्ध फास्फोरस (P)",
    soil_potassium: "उपलब्ध पोटेशियम (K)",
    soil_ph: "मृदा पीएच (pH)",
    soil_oc: "जैविक कार्बन (OC %)",
    soil_calculate: "मृदा स्वास्थ्य एवं क्षरण की गणना करें",
    soil_depletion_chart: "3-सीजन पोषक तत्व रुझान",
    soil_rotation_rec: "अनुशंसित फसल चक्र योजना",
    
    bi_title: "भारत कृषि-विश्लेषण: राष्ट्रीय फसल एवं आर्थिक डेटा",
    bi_subtitle: "फसल उत्पादन, किसान आय, मौसम एवं मृदा स्वास्थ्य का इंटरैक्टिव पावर बीआई हब",
    bi_tab_crop_prod: "फसल उत्पादन एवं जिले",
    bi_tab_farmer_econ: "किसान आय एवं भूमि",
    bi_tab_climate_impact: "मानसून एवं जलवायु प्रभाव",
    bi_tab_soil_radar: "मृदा स्वास्थ्य रडार मैट्रिक्स",
    bi_filter_state: "राज्य चुनें",
    bi_filter_season: "मौसम चुनें",
    bi_total_prod: "कुल उत्पादन",
    bi_cultivated_area: "कृषि क्षेत्र",
    bi_avg_yield: "राष्ट्रीय औसत उपज",
    bi_avg_income: "औसत किसान आय",
    
    chat_title: "कृषि मित्र — एआई कृषि सलाहकार",
    chat_subtitle: "आईसीएआर दिशानिर्देशों पर आधारित तत्काल बहुभाषी वैज्ञानिक सलाह",
    chat_placeholder: "फसल रोग, पीली पत्तियां, यूरिया खुराक या सरकारी योजनाओं के बारे में पूछें...",
    chat_send: "पूछें",
    
    status_online: "सिस्टम ऑनलाइन",
    status_cpu: "डिवाइस: पायटॉर्च रनटाइम",
    current_farm: "सक्रिय खेत",
    view_details: "विवरण देखें",
    all_states: "संपूर्ण भारत (राष्ट्रीय)"
  },
  kn: {
    app_title: "ಅಗ್ರಿಸ್ಫಿಯರ್ AI (AgriSphere AI)",
    tagline: "ಉಪಗ್ರಹ ರಿಮೋಟ್ ಸೆನ್ಸಿಂಗ್, ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಮತ್ತು ರಾಷ್ಟ್ರೀಯ ಕೃಷಿ ವಿಶ್ಲೇಷಣೆ",
    nav_command_center: "ಕಮಾಂಡ್ ಸೆಂಟರ್",
    nav_satellite_srm: "ಉಪಗ್ರಹ SRM ಸ್ಟುಡಿಯೋ",
    nav_soil_precision: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಮತ್ತು NPK",
    nav_national_analytics: "ರಾಷ್ಟ್ರೀಯ ಕೃಷಿ ವಿಶ್ಲೇಷಣೆ",
    nav_ai_agronomist: "ಕೃಷಿ ಮಿತ್ರ AI",
    nav_farms: "ನನ್ನ ಜಮೀನುಗಳು",
    nav_weather: "ಹವಾಮಾನ ರೇಡಾರ್",
    
    cmd_welcome: "ರಾಷ್ಟ್ರೀಯ ಕೃಷಿ ಕಮಾಂಡ್ ಸೆಂಟರ್",
    cmd_sub: "ಉಪಗ್ರಹ ಇಮೇಜರಿ, ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಮತ್ತು ರಾಷ್ಟ್ರೀಯ ಬೆಳೆ ಉತ್ಪಾದಕತೆಯ ಸಮಗ್ರ ವೇದಿಕೆ",
    cmd_active_farms: "ಮೇಲ್ವಿಚಾರಣೆಯಲ್ಲಿರುವ ಜಮೀನು",
    cmd_avg_soil_health: "ಸರಾಸರಿ ಮಣ್ಣಿನ ಆರೋಗ್ಯ",
    cmd_satellite_ready: "ಉಪಗ್ರಹ ನ್ಯೂರಾಲ್ ಎಂಜಿನ್",
    cmd_national_output: "ರಾಷ್ಟ್ರೀಯ ಆಹಾರ ಉತ್ಪಾದನೆ",
    cmd_quick_actions: "ತ್ವರಿತ ಕಾರ್ಯಗಳು",
    cmd_launch_srm: "ಉಪಗ್ರಹ ಸೂಪರ್-ರೆಸಲ್ಯೂಶನ್ ಚಲಾಯಿಸಿ",
    cmd_test_soil: "ಮಣ್ಣಿನ ಪೋಷಕಾಂಶ ಕ್ಷೀಣತೆಯನ್ನು ಪರೀಕ್ಷಿಸಿ",
    cmd_view_bi: "ರಾಷ್ಟ್ರೀಯ ವಿಶ್ಲೇಷಣೆ ವೀಕ್ಷಿಸಿ",
    cmd_ask_ai: "ಕೃಷಿ ಮಿತ್ರನಿಗೆ ಪ್ರಶ್ನಿಸಿ",
    
    srm_title: "GeoSR-AI: ಉಪಗ್ರಹ ಸೂಪರ್-ರೆಸಲ್ಯೂಶನ್ ಸ್ಟುಡಿಯೋ",
    srm_subtitle: "Sentinel-2 ಮತ್ತು Landsat ಉಪಗ್ರಹ ಚಿತ್ರಗಳ ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ ಆಧಾರಿತ ಸೂಪರ್-ರೆಸಲ್ಯೂಶನ್ ಮ್ಯಾಪಿಂಗ್",
    srm_select_scene: "ಉಪಗ್ರಹ ಕೃಷಿ ಪ್ರದೇಶವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    srm_or_upload: "ಅಥವಾ ನಿಮ್ಮ ಸ್ವಂತ ಫೈಲ್ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    srm_model_select: "ನ್ಯೂರಾಲ್ ಮಾಡೆಲ್",
    srm_scale_factor: "ಸ್ಕೇಲಿಂಗ್ ಅಂಶ (4x)",
    srm_run_btn: "ಸೂಪರ್-ರೆಸಲ್ಯೂಶನ್ ಪ್ರಾರಂಭಿಸಿ",
    srm_running: "ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
    srm_view_layers: "ದೃಶ್ಯ ಪದರಗಳು",
    srm_layer_rgb: "ಸೂಪರ್-ರೆಸಲ್ಯೂಶನ್ RGB",
    srm_layer_ndvi: "NDVI ಬೆಳೆ ಆರೋಗ್ಯ",
    srm_layer_nir: "ಫಾಲ್ಸ್-ಕಲರ್ NIR",
    srm_layer_unc: "ಅನಿಶ್ಚಿತತೆಯ ನಕ್ಷೆ",
    srm_metrics_header: "ಗುಣಮಟ್ಟದ ಮೆಟ್ರಿಕ್ಸ್",
    
    soil_title: "ನಿಖರ ಕೃಷಿ ಮತ್ತು 3-ಋತುಗಳ ಮಣ್ಣಿನ ಪೋಷಕಾಂಶಗಳ ಕ್ಷೀಣತೆ",
    soil_subtitle: "ಏಕಬೆಳೆ ಪೋಷಕಾಂಶ ಇಳಿಕೆ ಮುನ್ಸೂಚನೆ ಮತ್ತು ಬೆಳೆ ಪರಿವರ್ತನೆ ಯೋಜನೆ",
    soil_input_card: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಕಾರ್ಡ್ ವಿವರಗಳು",
    soil_nitrogen: "ಲಭ್ಯವಿರುವ ಸಾರಜನಕ (N)",
    soil_phosphorus: "ಲಭ್ಯವಿರುವ ರಂಜಕ (P)",
    soil_potassium: "ಲಭ್ಯವಿರುವ ಪೊಟ್ಯಾಶಿಯಂ (K)",
    soil_ph: "ಮಣ್ಣಿನ pH",
    soil_oc: "ಸಾವಯವ ಇಂಗಾಲ (OC %)",
    soil_calculate: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ",
    soil_depletion_chart: "3-ಋತುಗಳ ಪೋಷಕಾಂಶ ಕ್ಷೀಣತೆಯ ರೇಖಾಚಿತ್ರ",
    soil_rotation_rec: "ಶಿಫಾರಸು ಮಾಡಿದ ಬೆಳೆ ಪರಿವರ್ತನೆ",
    
    bi_title: "ಭಾರತ ಕೃಷಿ ವಿಶ್ಲೇಷಣೆ: ರಾಷ್ಟ್ರೀಯ ಬೆಳೆ ಮತ್ತು ಆರ್ಥಿಕ ಡೇಟಾ",
    bi_subtitle: "ಬೆಳೆ ಉತ್ಪಾದನೆ, ರೈತರ ಆದಾಯ, ಹವಾಮಾನ ಮತ್ತು ಮಣ್ಣಿನ ಮ್ಯಾಟ್ರಿಕ್ಸ್‌ನ ಇಂಟರ್ಯಾಕ್ಟಿವ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    bi_tab_crop_prod: "ಬೆಳೆ ಉತ್ಪಾದನೆ ಮತ್ತು ಜಿಲ್ಲೆಗಳು",
    bi_tab_farmer_econ: "ರೈತರ ಆದಾಯ ಮತ್ತು ಜಮೀನು",
    bi_tab_climate_impact: "ಮಾನ್ಸೂನ್ ಮತ್ತು ಹವಾಮಾನ ಪ್ರಭಾವ",
    bi_tab_soil_radar: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ರೇಡಾರ್ ಮ್ಯಾಟ್ರಿಕ್ಸ್",
    bi_filter_state: "ರಾಜ್ಯ ಆಯ್ಕೆಮಾಡಿ",
    bi_filter_season: "ಋತು ಆಯ್ಕೆಮಾಡಿ",
    bi_total_prod: "ಒಟ್ಟು ಉತ್ಪಾದನೆ",
    bi_cultivated_area: "ಕೃಷಿ ಪ್ರದೇಶ",
    bi_avg_yield: "ರಾಷ್ಟ್ರೀಯ ಸರಾಸರಿ ಇಳುವರಿ",
    bi_avg_income: "ರೈತರ ಸರಾಸರಿ ಆದಾಯ",
    
    chat_title: "ಕೃಷಿ ಮಿತ್ರ — AI ಕೃಷಿ ಸಲಹೆಗಾರ",
    chat_subtitle: "ICAR ಮಾರ್ಗಸೂಚಿಗಳ ಆಧಾರದ ಮೇಲೆ ತತ್ಕ್ಷಣದ ವೈಜ್ಞಾನಿಕ ಕೃಷಿ ಸಲಹೆ",
    chat_placeholder: "ಬೆಳೆ ರೋಗಗಳು, ಹಳದಿ ಎಲೆಗಳು, ಯೂರಿಯಾ ಡೋಸೇಜ್ ಅಥವಾ ಯೋಜನೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ...",
    chat_send: "ಕೇಳಿ",
    
    status_online: "ಆನ್‌ಲೈನ್",
    status_cpu: "ಸಾಧನ: PyTorch ರನ್‌ಟೈಮ್",
    current_farm: "ಸಕ್ರಿಯ ಜಮೀನು",
    view_details: "ವಿವರ ವೀಕ್ಷಿಸಿ",
    all_states: "ಸಮಗ್ರ ಭಾರತ (ರಾಷ್ಟ್ರೀಯ)"
  },
  ta: {
    app_title: "அக்ரிஸ்பியர் AI (AgriSphere AI)",
    tagline: "செயற்கைக்கோள் ரிமோட் சென்சிங், மண் வளம் மற்றும் தேசிய பயிர் நுண்ணறிவு",
    nav_command_center: "கட்டுப்பாட்டு மையம்",
    nav_satellite_srm: "செயற்கைக்கோள் SRM ஸ்டுடியோ",
    nav_soil_precision: "மண் வளம் & ஊட்டச்சத்து",
    nav_national_analytics: "தேசிய வேளாண் பகுப்பாய்வு",
    nav_ai_agronomist: "விவசாய AI ஆலோசகர்",
    nav_farms: "என் பண்ணைகள்",
    nav_weather: "வானிலை ரேடார்",
    
    cmd_welcome: "தேசிய வேளாண் கட்டுப்பாட்டு மையம்",
    cmd_sub: "செயற்கைக்கோள் இமேஜிங், மண் வளம் மற்றும் தேசிய பயிர் உற்பத்தித்திறனின் ஒருங்கிணைந்த தளம்",
    cmd_active_farms: "கண்காணிக்கப்படும் நிலம்",
    cmd_avg_soil_health: "சராசரி மண் ஆரோக்கிய குறியீடு",
    cmd_satellite_ready: "செயற்கைக்கோள் நியூரல் என்ஜின்",
    cmd_national_output: "தேசிய உணவு தானிய உற்பத்தி",
    cmd_quick_actions: "விரைவு செயல்பாடுகள்",
    cmd_launch_srm: "செயற்கைக்கோள் சூப்பர்-தெளிவுத்திறன் இயக்கு",
    cmd_test_soil: "மண் ஊட்டச்சத்து குறைவை சோதிக்கவும்",
    cmd_view_bi: "தேசிய பகுப்பாய்வு டாஷ்போர்டு திறக்கவும்",
    cmd_ask_ai: "விவசாய AI-யிடம் கேளுங்கள்",
    
    srm_title: "GeoSR-AI: செயற்கைக்கோள் சூப்பர்-தெளிவுத்திறன் ஸ்டுடியோ",
    srm_subtitle: "Sentinel-2 & Landsat செயற்கைக்கோள் படங்களின் AI சூப்பர்-தெளிவுத்திறன் மேப்பிங்",
    srm_select_scene: "செயற்கைக்கோள் விவசாய காட்சியைத் தேர்வுசெய்க",
    srm_or_upload: "அல்லது உங்கள் சொந்த படத்தை பதிவேற்றவும்",
    srm_model_select: "நியூரல் நெட்வொர்க் மாதிரி",
    srm_scale_factor: "அளவீட்டுக் காரணி (4x)",
    srm_run_btn: "செயல்முறையைத் தொடங்கு",
    srm_running: "செயலாக்கப்படுகிறது...",
    srm_view_layers: "காட்சி அடுக்குகள்",
    srm_layer_rgb: "சூப்பர்-தெளிவுத்திறன் RGB",
    srm_layer_ndvi: "NDVI பயிர் ஆரோக்கியம்",
    srm_layer_nir: "தவறான வண்ண NIR",
    srm_layer_unc: "நிச்சயமற்ற வெப்ப வரைபடம்",
    srm_metrics_header: "தர அளவீடுகள் & அளவுகோல்கள்",
    
    soil_title: "துல்லிய வேளாண்மை & 3-பருவ மண் ஊட்டச்சத்து குறைவு",
    soil_subtitle: "தொடர் ஒற்றைப் பயிர் ஊட்டச்சத்து குறைவு கணிப்பு மற்றும் பயிர் சுழற்சி திட்டம்",
    soil_input_card: "மண் ஆரோக்கிய அட்டை உள்ளீடு",
    soil_nitrogen: "நைட்ரஜன் (N)",
    soil_phosphorus: "பாஸ்பரஸ் (P)",
    soil_potassium: "பொட்டாசியம் (K)",
    soil_ph: "மண் கார அமிலத்தன்மை (pH)",
    soil_oc: "கரிம கார்பன் (OC %)",
    soil_calculate: "மண் ஆரோக்கியத்தை கணக்கிடுக",
    soil_depletion_chart: "3-பருவ ஊட்டச்சத்து குறைவு வரைபடம்",
    soil_rotation_rec: "பரிந்துரைக்கப்பட்ட பயிர் சுழற்சி",
    
    bi_title: "பாரத வேளாண் பகுப்பாய்வு: தேசிய பயிர் & பொருளாதார தரவு",
    bi_subtitle: "பயிர் உற்பத்தி, விவசாயிகள் வருமானம், பருவமழை மற்றும் மண் மேட்ரிக்ஸின் விரிவான டாஷ்போர்டு",
    bi_tab_crop_prod: "பயிர் உற்பத்தி & மாவட்டங்கள்",
    bi_tab_farmer_econ: "விவசாயிகள் வருமானம் & நிலம்",
    bi_tab_climate_impact: "பருவமழை & காலநிலை தாக்கம்",
    bi_tab_soil_radar: "மண் ஆரோக்கிய ரேடார் மேட்ரிக்ஸ்",
    bi_filter_state: "மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
    bi_filter_season: "பருவத்தைத் தேர்ந்தெடுக்கவும்",
    bi_total_prod: "மொத்த உற்பத்தி",
    bi_cultivated_area: "பயிரிடப்பட்ட பரப்பளவு",
    bi_avg_yield: "தேசிய சராசரி மகசூல்",
    bi_avg_income: "விவசாயிகளின் சராசரி வருமானம்",
    
    chat_title: "விவசாய AI ஆலோசகர் (Krishi Mitra)",
    chat_subtitle: "ICAR வழிகாட்டுதல்களின் அடிப்படையிலான உடனடி பலமொழி அறிவியல் ஆலோசனை",
    chat_placeholder: "பயிர் நோய்கள், மஞ்சள் இலைகள், உர அளவு அல்லது திட்டங்கள் பற்றி கேளுங்கள்...",
    chat_send: "கேளுங்கள்",
    
    status_online: "ஆன்லைன்",
    status_cpu: "சாதனம்: PyTorch இயக்க முறை",
    current_farm: "செயலில் உள்ள பண்ணை",
    view_details: "விவரங்களைக் காண்க",
    all_states: "முழு இந்தியா (தேசிய)"
  },
  te: {
    app_title: "అగ్రిస్ఫియర్ AI (AgriSphere AI)",
    tagline: "ఉపగ్రహ రిమోట్ సెన్సింగ్, నేల ఆరోగ్యం మరియు జాతీయ పంట విశ్లేషణ",
    nav_command_center: "కమాండ్ సెంటర్",
    nav_satellite_srm: "ఉపగ్రహ SRM స్టూడియో",
    nav_soil_precision: "నేల ఆరోగ్యం & NPK",
    nav_national_analytics: "జాతీయ వ్యవసాయ విశ్లేషణ",
    nav_ai_agronomist: "కృషి మిత్ర AI",
    nav_farms: "నా పొలాలు",
    nav_weather: "వాతావరణ రాడార్",
    
    cmd_welcome: "జాతీయ వ్యవసాయ కమాండ్ సెంటర్",
    cmd_sub: "ఉపగ్రహ ఇమేజింగ్, నేల ఆరోగ్యం మరియు జాతీయ పంట ఉత్పాదకత యొక్క సమగ్ర వేదిక",
    cmd_active_farms: "పర్యవేక్షణలో ఉన్న భూమి",
    cmd_avg_soil_health: "సగటు నేల ఆరోగ్య సూచిక",
    cmd_satellite_ready: "ఉపగ్రహ న్యూరల్ ఇంజిన్",
    cmd_national_output: "జాతీయ ఆహార ధాన్యాల ఉత్పత్తి",
    cmd_quick_actions: "త్వరిత చర్యలు",
    cmd_launch_srm: "ఉపగ్రహ సూపర్-రిజల్యూషన్ ప్రారంభించండి",
    cmd_test_soil: "నేల పోషకాల క్షీణతను పరీక్షించండి",
    cmd_view_bi: "జాతీయ విశ్లేషణ డాష్‌బోర్డ్ తెరవండి",
    cmd_ask_ai: "కృషి మిత్రను అడగండి",
    
    srm_title: "GeoSR-AI: ఉపగ్రహ సూపర్-రిజల్యూషన్ స్టూడియో",
    srm_subtitle: "Sentinel-2 & Landsat ఉపగ్రహ చిత్రాల AI ఆధారిత సూపర్-రిజల్యూషన్ మ్యాపింగ్",
    srm_select_scene: "ఉపగ్రహ వ్యవసాయ ప్రాంతాన్ని ఎంచుకోండి",
    srm_or_upload: "లేదా మీ స్వంత చిత్రాన్ని అప్‌లోడ్ చేయండి",
    srm_model_select: "న్యూరల్ నెట్‌వర్క్ మోడల్",
    srm_scale_factor: "స్కేలింగ్ ఫ్యాక్టర్ (4x)",
    srm_run_btn: "సూపర్-రిజల్యూషన్ ప్రారంభించండి",
    srm_running: "ప్రాసెస్ చేయబడుతోంది...",
    srm_view_layers: "దృశ్య పొరలు",
    srm_layer_rgb: "సూపర్-రిజల్యూషన్ RGB",
    srm_layer_ndvi: "NDVI పంట ఆరోగ్యం",
    srm_layer_nir: "ఫాల్స్-కలర్ NIR",
    srm_layer_unc: "అనిశ్చితి హీట్‌మ్యాప్",
    srm_metrics_header: "నాణ్యత ప్రమాణాలు & కొలమానాలు",
    
    soil_title: "ఖచ్చితమైన వ్యవసాయం & 3-సీజన్ల నేల పోషకాల క్షీణత",
    soil_subtitle: "ఏక పంట పోషకాల తగ్గుదల అంచనా మరియు పంట మార్పిడి ప్రణాళిక",
    soil_input_card: "నేల ఆరోగ్య కార్డు వివరాలు",
    soil_nitrogen: "నైట్రోజన్ (N)",
    soil_phosphorus: "భాస్వరం (P)",
    soil_potassium: "పొటాషియం (K)",
    soil_ph: "నేల pH",
    soil_oc: "సేంద్రీయ కార్బన్ (OC %)",
    soil_calculate: "నేల ఆరోగ్యాన్ని లెక్కించండి",
    soil_depletion_chart: "3-సీజన్ల పోషకాల క్షీణత గ్రాఫ్",
    soil_rotation_rec: "సిఫార్సు చేయబడిన పంట మార్పిడి",
    
    bi_title: "భారత వ్యవసాయ విశ్లేషణ: జాతీయ పంట & ఆర్థిక సమాచారం",
    bi_subtitle: "పంట ఉత్పత్తి, రైతుల ఆదాయం, రుతుపవనాలు మరియు నేల ఆరోగ్యం యొక్క ఇంటరాక్టివ్ డాష్‌బోర్డ్",
    bi_tab_crop_prod: "పంట ఉత్పత్తి & జిల్లాలు",
    bi_tab_farmer_econ: "రైతుల ఆదాయం & భూమి",
    bi_tab_climate_impact: "రుతుపవనాలు & వాతావరణ ప్రభావం",
    bi_tab_soil_radar: "నేల ఆరోగ్య రాడార్ మ్యాట్రిక్స్",
    bi_filter_state: "రాష్ట్రాన్ని ఎంచుకోండి",
    bi_filter_season: "సీజన్ ఎంచుకోండి",
    bi_total_prod: "మొత్తం ఉత్పత్తి",
    bi_cultivated_area: "సాగు విస్తీర్ణం",
    bi_avg_yield: "జాతీయ సగటు దిగుబడి",
    bi_avg_income: "రైతు సగటు ఆదాయం",
    
    chat_title: "కృషి మిత్ర — AI వ్యవసాయ సలహాదారు",
    chat_subtitle: "ICAR మార్గదర్శకాల ఆధారంగా తక్షణ బహుభాషా శాస్త్రీయ వ్యవసాయ సలహా",
    chat_placeholder: "పంట తెగుళ్ళు, పసుపు ఆకులు, ఎరువుల మోతాదు లేదా పథకాల గురించి అడగండి...",
    chat_send: "అడగండి",
    
    status_online: "ఆన్‌లైన్",
    status_cpu: "పరికరం: PyTorch రన్‌టైమ్",
    current_farm: "ప్రస్తుత పొలం",
    view_details: "వివరాలు చూడండి",
  },
  mr: {
    app_title: "अ‍ॅग्रीस्फिअर AI (AgriSphere AI)",
    tagline: "भू-स्थानिक रिमोट सेन्सिंग, मृदा आरोग्य आणि राष्ट्रीय कृषी विश्लेषण",
    nav_command_center: "कमांड सेंटर",
    nav_satellite_srm: "जिओएसआर उपग्रह स्टुडिओ",
    nav_soil_precision: "मृदा आरोग्य व पोषण",
    nav_national_analytics: "राष्ट्रीय पीक विश्लेषण",
    nav_ai_agronomist: "कृषी मित्र AI",
    nav_farms: "माझी शेतं",
    nav_weather: "हवामान रडार",
    cmd_welcome: "राष्ट्रीय कृषी कमांड सेंटर",
    cmd_sub: "उपग्रह रिमोट सेन्सिंग, अचूक माती आरोग्य आणि आर्थिक विश्लेषणाचे एकात्मिक व्यासपीठ",
    cmd_active_farms: "देखरेखीखालील शेतीजमीन",
    cmd_avg_soil_health: "सरासरी मृदा आरोग्य निर्देशांक",
    cmd_satellite_ready: "उपग्रह न्यूरल इंजिन",
    cmd_national_output: "राष्ट्रीय अन्नधान्य उत्पादन",
    cmd_quick_actions: "जलद कृती",
    cmd_launch_srm: "उपग्रह सुपर-रेझोल्यूशन चालवा",
    cmd_test_soil: "मृदा पोषण घट तपासा",
    cmd_view_bi: "राष्ट्रीय विश्लेषण उघडा",
    cmd_ask_ai: "कृषी मित्राला विचारा",
    srm_title: "GeoSR-AI: उपग्रह प्रतिमा सुपर-रेझोल्यूशन स्टुडिओ",
    srm_subtitle: "Sentinel-2 आणि Landsat उपग्रह प्रतिमांचे AI आधारित सुपर-रेझोल्यूशन मॅपिंग",
    srm_select_scene: "उपग्रह कृषी दृश्य निवडा",
    srm_or_upload: "किंवा स्वतःची प्रतिमा अपलोड करा",
    srm_model_select: "न्यूरल मॉडेल",
    srm_scale_factor: "स्केलिंग घटक (4x)",
    srm_run_btn: "सुपर-रेझोल्यूशन सुरू करा",
    srm_running: "प्रक्रिया सुरू आहे...",
    srm_view_layers: "दृश्य स्तर",
    srm_layer_rgb: "सुपर-रेझोल्यूशन RGB",
    srm_layer_ndvi: "NDVI पीक आरोग्य",
    srm_layer_nir: "फॉल्स-कलर NIR",
    srm_layer_unc: "अनिश्चितता नकाशा",
    srm_metrics_header: "गुणवत्ता मेट्रिक्स",
    soil_title: "अचूक कृषी आणि 3-हंगामातील मृदा पोषण घट",
    soil_subtitle: "सलग एकाच पिकाने होणारी पोषण घट आणि पीक फेरपालट योजना",
    soil_input_card: "मृदा आरोग्य पत्रिका तपशील",
    soil_nitrogen: "उपलब्ध नायट्रोजन (N)",
    soil_phosphorus: "उपलब्ध फॉस्फरस (P)",
    soil_potassium: "उपलब्ध पोटॅशियम (K)",
    soil_ph: "मातीचा pH",
    soil_oc: "सेंद्रिय कर्ब (OC %)",
    soil_calculate: "मृदा आरोग्याची गणना करा",
    soil_depletion_chart: "3-हंगामातील पोषण घट आलेख",
    soil_rotation_rec: "शिफारस केलेली पीक फेरपालट",
    bi_title: "भारत कृषी विश्लेषण: राष्ट्रीय पीक आणि आर्थिक डेटा",
    bi_subtitle: "पीक उत्पादन, शेतकरी उत्पन्न, हवामान आणि माती मॅट्रिक्सचे परस्परसंवादी डॅशबोर्ड",
    bi_tab_crop_prod: "पीक उत्पादन आणि जिल्हे",
    bi_tab_farmer_econ: "शेतकरी उत्पन्न आणि जमीन",
    bi_tab_climate_impact: "पावसाळा आणि हवामान प्रभाव",
    bi_tab_soil_radar: "मृदा आरोग्य रडार मॅट्रिक्स",
    bi_filter_state: "राज्य निवडा",
    bi_filter_season: "हंगाम निवडा",
    bi_total_prod: "एकूण उत्पादन",
    bi_cultivated_area: "लागवड क्षेत्र",
    bi_avg_yield: "राष्ट्रीय सरासरी उत्पादन",
    bi_avg_income: "शेतकरी सरासरी उत्पन्न",
    chat_title: "कृषी मित्र — AI कृषी सल्लागार",
    chat_subtitle: "ICAR मार्गदर्शक तत्त्वांवर आधारित त्वरित बहुभाषिक वैज्ञानिक सल्ला",
    chat_placeholder: "पिकांवरील रोग, खतांचा डोस, किंवा योजनांविषयी विचारा...",
    chat_send: "विचारा",
    status_online: "ऑनलाइन",
    status_cpu: "डिव्हाइस: PyTorch रनटाइम",
    current_farm: "सक्रिय शेत",
    view_details: "तपशील पहा",
    all_states: "संपूर्ण भारत (राष्ट्रीय)"
  },
  bn: {
    app_title: "অ্যাগ্রিস্ফিয়ার এআই (AgriSphere AI)",
    tagline: "ভূ-স্থানিক স্যাটেলাইট রিমোট সেন্সিং, মাটির স্বাস্থ্য এবং জাতীয় ফসল বিশ্লেষণ",
    nav_command_center: "কমান্ড সেন্টার",
    nav_satellite_srm: "জিওএসআর স্যাটেলাইট স্টুডিও",
    nav_soil_precision: "মাটির স্বাস্থ্য ও পুষ্টি",
    nav_national_analytics: "জাতীয় ফসল বিশ্লেষণ",
    nav_ai_agronomist: "কৃষি মিত্র এআই",
    nav_farms: "আমার খামার",
    nav_weather: "আবহাওয়া রাডার",
    cmd_welcome: "জাতীয় কৃষি কমান্ড সেন্টার",
    cmd_sub: "স্যাটেলাইট রিমোট সেন্সিং ও মাটির স্বাস্থ্যের সমন্বিত প্ল্যাটফর্ম",
    cmd_active_farms: "তত্ত্বাবধানে থাকা জমি",
    cmd_avg_soil_health: "গড় মাটির স্বাস্থ্য সূচক",
    cmd_satellite_ready: "স্যাটেলাইট নিউরাল ইঞ্জিন",
    cmd_national_output: "জাতীয় খাদ্যশস্য উৎপাদন",
    cmd_quick_actions: "দ্রুত পদক্ষেপ",
    cmd_launch_srm: "স্যাটেলাইট সুপার-রেজোলিউশন চালান",
    cmd_test_soil: "মাটির পুষ্টি ক্ষয় পরীক্ষা করুন",
    cmd_view_bi: "জাতীয় বিশ্লেষণ ড্যাশবোর্ড খুলুন",
    cmd_ask_ai: "কৃষি মিত্রকে জিজ্ঞাসা করুন",
    srm_title: "GeoSR-AI: স্যাটেলাইট সুপার-রেজোলিউশন স্টুডিও",
    srm_subtitle: "Sentinel-2 এবং Landsat স্যাটেলাইট ছবির AI সুপার-রেজোলিউশন",
    srm_select_scene: "স্যাটেলাইট কৃষি দৃশ্য নির্বাচন করুন",
    srm_or_upload: "বা আপনার ছবি আপলোড করুন",
    srm_model_select: "নিউরাল নেটওয়ার্ক মডেল",
    srm_scale_factor: "স্কেলিং গুণক (4x)",
    srm_run_btn: "সুপার-রেজোলিউশন প্রক্রিয়া শুরু করুন",
    srm_running: "প্রক্রিয়াকরণ চলছে...",
    srm_view_layers: "দৃশ্যমান স্তর",
    srm_layer_rgb: "সুপার-রেজোলিউশন RGB",
    srm_layer_ndvi: "NDVI ফসলের স্বাস্থ্য",
    srm_layer_nir: "ফলস-কালার NIR",
    srm_layer_unc: "অনিশ্চয়তার মানচিত্র",
    srm_metrics_header: "গুণমান মেট্রিক্স",
    soil_title: "নির্ভুল কৃষি এবং ৩-মৌসুমের মাটির পুষ্টি ক্ষয়",
    soil_subtitle: "একক ফসলের পুষ্টি ক্ষয় পূর্বাভাস এবং ফসল আবর্তন পরিকল্পনা",
    soil_input_card: "মাটির স্বাস্থ্য কার্ডের বিবরণ",
    soil_nitrogen: "উপলব্ধ নাইট্রোজেন (N)",
    soil_phosphorus: "উপলব্ধ ফসফরাস (P)",
    soil_potassium: "উপলব্ধ পটাশিয়াম (K)",
    soil_ph: "মাটির pH",
    soil_oc: "জৈব কার্বন (OC %)",
    soil_calculate: "মাটির স্বাস্থ্য গণনা করুন",
    soil_depletion_chart: "৩-মৌসুমের পুষ্টি ক্ষয় চার্ট",
    soil_rotation_rec: "প্রস্তাবিত ফসল আবর্তন",
    bi_title: "ভারত কৃষি বিশ্লেষণ: জাতীয় ফসল ও অর্থনৈতিক ডেটা",
    bi_subtitle: "ফসল উৎপাদন, কৃষকের আয়, আবহাওয়া এবং মাটির ম্যাট্রিক্সের ড্যাশবোর্ড",
    bi_tab_crop_prod: "ফসল উৎপাদন ও জেলা",
    bi_tab_farmer_econ: "কৃষকের আয় ও জমি",
    bi_tab_climate_impact: "বর্ষা ও জলবায়ুর প্রভাব",
    bi_tab_soil_radar: "মাটির স্বাস্থ্য রাডার ম্যাট্রিক্স",
    bi_filter_state: "রাজ্য নির্বাচন করুন",
    bi_filter_season: "ঋতু নির্বাচন করুন",
    bi_total_prod: "মোট উৎপাদন",
    bi_cultivated_area: "চাষের এলাকা",
    bi_avg_yield: "জাতীয় গড় ফলন",
    bi_avg_income: "কৃষকের গড় আয়",
    chat_title: "কৃষি মিত্র — এআই কৃষি পরামর্শদাতা",
    chat_subtitle: "ICAR নির্দেশিকার ভিত্তিতে তাৎক্ষণিক বৈজ্ঞানিক পরামর্শ",
    chat_placeholder: "ফসলের রোগ, সারের ডোজ বা সরকারি প্রকল্প সম্পর্কে জিজ্ঞাসা করুন...",
    chat_send: "জিজ্ঞাসা করুন",
    status_online: "অনলাইন",
    status_cpu: "ডিভাইস: PyTorch রানটাইম",
    current_farm: "সক্রিয় খামার",
    view_details: "বিস্তারিত দেখুন",
    all_states: "সমগ্র ভারত (জাতীয়)"
  },
  pa: {
    app_title: "ਐਗਰੀਸਫੀਅਰ ਏਆਈ (AgriSphere AI)",
    tagline: "ਸੈਟੇਲਾਈਟ ਰਿਮੋਟ ਸੈਂਸਿੰਗ, ਮਿੱਟੀ ਦੀ ਸਿਹਤ ਅਤੇ ਰਾਸ਼ਟਰੀ ਫਸਲ ਵਿਸ਼ਲੇਸ਼ਣ",
    nav_command_center: "ਕਮਾਂਡ ਸੈਂਟਰ",
    nav_satellite_srm: "ਜੀਓਐਸਆਰ ਸੈਟੇਲਾਈਟ ਸਟੂਡੀਓ",
    nav_soil_precision: "ਮਿੱਟੀ ਦੀ ਸਿਹਤ ਅਤੇ NPK",
    nav_national_analytics: "ਰਾਸ਼ਟਰੀ ਫਸਲ ਵਿਸ਼ਲੇਸ਼ਣ",
    nav_ai_agronomist: "ਕ੍ਰਿਸ਼ੀ ਮਿੱਤਰ ਏਆਈ",
    nav_farms: "ਮੇਰੇ ਖੇਤ",
    nav_weather: "ਮੌਸਮ ਰਾਡਾਰ",
    cmd_welcome: "ਰਾਸ਼ਟਰੀ ਖੇਤੀਬਾੜੀ ਕਮਾਂਡ ਸੈਂਟਰ",
    cmd_sub: "ਸੈਟੇਲਾਈਟ ਰਿਮੋਟ ਸੈਂਸਿੰਗ ਅਤੇ ਮਿੱਟੀ ਦੀ ਸਿਹਤ ਦਾ ਏਕੀਕ੍ਰਿਤ ਪਲੇਟਫਾਰਮ",
    cmd_active_farms: "ਨਿਗਰਾਨੀ ਹੇਠ ਖੇਤੀ ਜ਼ਮੀਨ",
    cmd_avg_soil_health: "ਔਸਤ ਮਿੱਟੀ ਸਿਹਤ ਸੂਚਕਾਂਕ",
    cmd_satellite_ready: "ਸੈਟੇਲਾਈਟ ਨਿਊਰਲ ਇੰਜਣ",
    cmd_national_output: "ਰਾਸ਼ਟਰੀ ਅਨਾਜ ਉਤਪਾਦਨ",
    cmd_quick_actions: "ਤੇਜ਼ ਕਾਰਵਾਈਆਂ",
    cmd_launch_srm: "ਸੈਟੇਲਾਈਟ ਸੁਪਰ-ਰੈਜ਼ੋਲਿਊਸ਼ਨ ਚਲਾਓ",
    cmd_test_soil: "ਮਿੱਟੀ ਦੇ ਪੋਸ਼ਕ ਤੱਤਾਂ ਦੀ ਕਮੀ ਜਾਂਚੋ",
    cmd_view_bi: "ਰਾਸ਼ਟਰੀ ਵਿਸ਼ਲੇਸ਼ਣ ਡੈਸ਼ਬੋਰਡ ਖੋਲ੍ਹੋ",
    cmd_ask_ai: "ਕ੍ਰਿਸ਼ੀ ਮਿੱਤਰ ਤੋਂ ਪੁੱਛੋ",
    srm_title: "GeoSR-AI: ਸੈਟੇਲਾਈਟ ਸੁਪਰ-ਰੈਜ਼ੋਲਿਊਸ਼ਨ ਸਟੂਡੀਓ",
    srm_subtitle: "Sentinel-2 ਅਤੇ Landsat ਸੈਟੇਲਾਈਟ ਚਿੱਤਰਾਂ ਦੀ AI ਸੁਪਰ-ਰੈਜ਼ੋਲਿਊਸ਼ਨ ਮੈਪਿੰਗ",
    srm_select_scene: "ਸੈਟੇਲਾਈਟ ਖੇਤੀ ਦ੍ਰਿਸ਼ ਚੁਣੋ",
    srm_or_upload: "ਜਾਂ ਆਪਣੀ ਤਸਵੀਰ ਅੱਪਲੋਡ ਕਰੋ",
    srm_model_select: "ਨਿਊਰਲ ਮਾਡਲ",
    srm_scale_factor: "ਸਕੇਲਿੰਗ ਗੁਣਕ (4x)",
    srm_run_btn: "ਸੁਪਰ-ਰੈਜ਼ੋਲਿਊਸ਼ਨ ਸ਼ੁਰੂ ਕਰੋ",
    srm_running: "ਪ੍ਰਕਿਰਿਆ ਚੱਲ ਰਹੀ ਹੈ...",
    srm_view_layers: "ਦ੍ਰਿਸ਼ ਪਰਤਾਂ",
    srm_layer_rgb: "ਸੁਪਰ-ਰੈਜ਼ੋਲਿਊਸ਼ਨ RGB",
    srm_layer_ndvi: "NDVI ਫਸਲ ਸਿਹਤ",
    srm_layer_nir: "ਫਾਲਸ-ਕਲਰ NIR",
    srm_layer_unc: "ਅਨਿਸ਼ਚਿਤਤਾ ਨਕਸ਼ਾ",
    srm_metrics_header: "ਗੁਣਵੱਤਾ ਮੈਟ੍ਰਿਕਸ",
    soil_title: "ਸਟੀਕ ਖੇਤੀਬਾੜੀ ਅਤੇ 3-ਸੀਜ਼ਨ ਮਿੱਟੀ ਪੋਸ਼ਕ ਤੱਤਾਂ ਦੀ ਕਮੀ",
    soil_subtitle: "ਇੱਕੋ ਫਸਲ ਦੇ ਨੁਕਸਾਨ ਦਾ ਅਨੁਮਾਨ ਅਤੇ ਫਸਲੀ ਚੱਕਰ ਯੋਜਨਾ",
    soil_input_card: "ਮਿੱਟੀ ਸਿਹਤ ਕਾਰਡ ਵੇਰਵੇ",
    soil_nitrogen: "ਉਪਲਬਧ ਨਾਈਟ੍ਰੋਜਨ (N)",
    soil_phosphorus: "ਉਪਲਬਧ ਫਾਸਫੋਰਸ (P)",
    soil_potassium: "ਉਪਲਬਧ ਪੋਟਾਸ਼ੀਅਮ (K)",
    soil_ph: "ਮਿੱਟੀ ਦਾ pH",
    soil_oc: "ਜੈਵਿਕ ਕਾਰਬਨ (OC %)",
    soil_calculate: "ਮਿੱਟੀ ਸਿਹਤ ਦੀ ਗਣਨਾ ਕਰੋ",
    soil_depletion_chart: "3-ਸੀਜ਼ਨ ਪੋਸ਼ਕ ਤੱਤਾਂ ਦਾ ਰੁਝਾਨ",
    soil_rotation_rec: "ਸਿਫਾਰਸ਼ ਕੀਤਾ ਫਸਲੀ ਚੱਕਰ",
    bi_title: "ਭਾਰਤ ਖੇਤੀਬਾੜੀ ਵਿਸ਼ਲੇਸ਼ਣ: ਰਾਸ਼ਟਰੀ ਫਸਲ ਅਤੇ ਆਰਥਿਕ ਡਾਟਾ",
    bi_subtitle: "ਫਸਲ ਉਤਪਾਦਨ, ਕਿਸਾਨ ਆਮਦਨ, ਮੌਸਮ ਅਤੇ ਮਿੱਟੀ ਮੈਟ੍ਰਿਕਸ ਦਾ ਇੰਟਰਐਕਟਿਵ ਡੈਸ਼ਬੋਰਡ",
    bi_tab_crop_prod: "ਫਸਲ ਉਤਪਾਦਨ ਅਤੇ ਜ਼ਿਲ੍ਹੇ",
    bi_tab_farmer_econ: "ਕਿਸਾਨ ਆਮਦਨ ਅਤੇ ਜ਼ਮੀਨ",
    bi_tab_climate_impact: "ਮਾਨਸੂਨ ਅਤੇ ਜਲਵਾਯੂ ਪ੍ਰਭਾਵ",
    bi_tab_soil_radar: "ਮਿੱਟੀ ਸਿਹਤ ਰਾਡਾਰ ਮੈਟ੍ਰਿਕਸ",
    bi_filter_state: "ਰਾਜ ਚੁਣੋ",
    bi_filter_season: "ਸੀਜ਼ਨ ਚੁਣੋ",
    bi_total_prod: "ਕੁੱਲ ਉਤਪਾਦਨ",
    bi_cultivated_area: "ਕਾਸ਼ਤਯੋਗ ਰਕਬਾ",
    bi_avg_yield: "ਰਾਸ਼ਟਰੀ ਔਸਤ ਝਾੜ",
    bi_avg_income: "ਕਿਸਾਨ ਦੀ ਔਸਤ ਆਮਦਨ",
    chat_title: "ਕ੍ਰਿਸ਼ੀ ਮਿੱਤਰ — ਏਆਈ ਖੇਤੀ ਸਲਾਹਕਾਰ",
    chat_subtitle: "ICAR ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼ਾਂ ਦੇ ਆਧਾਰ ਤੇ ਤੁਰੰਤ ਵਿਗਿਆਨਕ ਸਲਾਹ",
    chat_placeholder: "ਫਸਲਾਂ ਦੀਆਂ ਬਿਮਾਰੀਆਂ, ਖਾਦਾਂ ਜਾਂ ਸਕੀਮਾਂ ਬਾਰੇ ਪੁੱਛੋ...",
    chat_send: "ਪੁੱਛੋ",
    status_online: "ਆਨਲਾਈਨ",
    status_cpu: "ਡਿਵਾਈਸ: PyTorch ਰਨਟਾਈਮ",
    current_farm: "ਸਰਗਰਮ ਖੇਤ",
    view_details: "ਵੇਰਵੇ ਦੇਖੋ",
    all_states: "ਪੂਰਾ ਭਾਰਤ (ਰਾਸ਼ਟਰੀ)"
  },
  gu: {
    app_title: "એગ્રીસ્ફિયર AI (AgriSphere AI)",
    tagline: "ભૂ-સ્થાનિક સેટેલાઇટ રિમોટ સેન્સિંગ, જમીન આરોગ્ય અને રાષ્ટ્રીય પાક વિશ્લેષણ",
    nav_command_center: "કમાન્ડ સેન્ટર",
    nav_satellite_srm: "જીઓએસઆર સેટેલાઇટ સ્ટુડિયો",
    nav_soil_precision: "જમીન આરોગ્ય અને પોષક તત્વો",
    nav_national_analytics: "રાષ્ટ્રીય પાક વિશ્લેષણ",
    nav_ai_agronomist: "કૃષિ મિત્ર AI",
    nav_farms: "મારા ખેતરો",
    nav_weather: "હવામાન રડાર",
    cmd_welcome: "રાષ્ટ્રીય કૃષિ કમાન્ડ સેન્ટર",
    cmd_sub: "સેટેલાઇટ રિમોਟ સેન્સિંગ અને જમીન આરોગ્યનું સંકલિત પ્લેટફોર્મ",
    cmd_active_farms: "દેખરેખ હેઠળ ખેતીની જમીન",
    cmd_avg_soil_health: "સરેરાશ જમીન આરોગ્ય સૂચકાંક",
    cmd_satellite_ready: "સેટેલાઇટ ન્યુરલ એન્જિન",
    cmd_national_output: "રાષ્ટ્રીય અનાજ ઉત્પાદન",
    cmd_quick_actions: "ઝડપી ક્રિયાઓ",
    cmd_launch_srm: "સેટેલાઇટ સુપર-રિઝોલ્યુશન ચલાવો",
    cmd_test_soil: "જમીન પોષક તત્વોની ખામી તપાસો",
    cmd_view_bi: "રાષ્ટ્રીય વિશ્લેષણ ડેશબોર્ડ ખોલો",
    cmd_ask_ai: "કૃષિ મિત્રને પૂછો",
    srm_title: "GeoSR-AI: સેટેલાઇટ સુપર-રિઝોલ્યુશન સ્ટુડિયો",
    srm_subtitle: "Sentinel-2 અને Landsat સેટેલાઇટ છબીઓનું AI સુપર-રિઝોલ્યુશન મેપિંગ",
    srm_select_scene: "સેટેલાઇટ કૃષિ દ્રશ્ય પસંદ કરો",
    srm_or_upload: "અથવા તમારી છબી અપલોડ કરો",
    srm_model_select: "ન્યુરલ મોડેલ",
    srm_scale_factor: "સ્કેલિંગ પરિબળ (4x)",
    srm_run_btn: "સુપર-રિઝોલ્યુશન શરૂ કરો",
    srm_running: "પ્રક્રિયા ચાલુ છે...",
    srm_view_layers: "દ્રશ્ય સ્તરો",
    srm_layer_rgb: "સુપર-રિઝોલ્યુશન RGB",
    srm_layer_ndvi: "NDVI પાક આરોગ્ય",
    srm_layer_nir: "ફોલ્સ-કલર NIR",
    srm_layer_unc: "અનિશ્ચિતતા નકશો",
    srm_metrics_header: "ગુણવત્તા મેટ્રિક્સ",
    soil_title: "ચોક્કસ કૃષિ અને 3-સીઝન જમીન પોષક તત્વોની ખામી",
    soil_subtitle: "એક પાકના નુકસાનનું પૂર્વાનુમાન અને પાક ફેરબદલી યોજના",
    soil_input_card: "જમીન આરોગ્ય કાર્ડ વિગતો",
    soil_nitrogen: "ઉપલબ્ધ નાઇટ્રોજન (N)",
    soil_phosphorus: "ઉપલબ્ધ ફોસ્ફરસ (P)",
    soil_potassium: "ઉપલબ્ધ પોટેશિયમ (K)",
    soil_ph: "જમીનનું pH",
    soil_oc: "ઓર્ગેનિક કાર્બન (OC %)",
    soil_calculate: "જમીન આરોગ્યની ગણતરી કરો",
    soil_depletion_chart: "3-સીઝન પોષક તત્વોનો ઘટાડો આલેખ",
    soil_rotation_rec: "ભલામણ કરેલ પાક ફેરબદલી",
    bi_title: "ભારત કૃષિ વિશ્લેષણ: રાષ્ટ્રીય પાક અને આર્થિક ડેટા",
    bi_subtitle: "પાક ઉત્પાદન, ખેડૂત આવક, હવામાન અને જમીન મેટ્રિક્સનું ડેશબોર્ડ",
    bi_tab_crop_prod: "પાક ઉત્પાદન અને જિલ્લાઓ",
    bi_tab_farmer_econ: "ખેડૂત આવક અને જમીન",
    bi_tab_climate_impact: "ચોમાસું અને આબોહવા પ્રભાવ",
    bi_tab_soil_radar: "જમીન આરોગ્ય રડાર મેટ્રિક્સ",
    bi_filter_state: "રાજ્ય પસંદ કરો",
    bi_filter_season: "સીઝન પસંદ કરો",
    bi_total_prod: "કુલ ઉત્પાદન",
    bi_cultivated_area: "વાવેતર વિસ્તાર",
    bi_avg_yield: "રાષ્ટ્રીય સરેરાશ ઉપજ",
    bi_avg_income: "ખેડૂતની સરેરાશ આવક",
    chat_title: "કૃષિ મિત્ર — AI કૃષિ સલાહકાર",
    chat_subtitle: "ICAR માર્ગદર્શિકા પર આધારિત ત્વરિત વૈજ્ઞાનિક સલાહ",
    chat_placeholder: "પાકના રોગો, ખાતરના ડોઝ અથવા સરકારી યોજનાઓ વિશે પૂછો...",
    chat_send: "પૂછો",
    status_online: "ઓનલાઇન",
    status_cpu: "ઉપકરણ: PyTorch રનટાઇમ",
    current_farm: "સક્રિય ખેતર",
    view_details: "વિગતો જુઓ",
    all_states: "સમગ્ર ભારત (રાષ્ટ્રીય)"
  },
  ml: {
    app_title: "അഗ്രിസ്ഫിയർ AI (AgriSphere AI)",
    tagline: "ഉപഗ്രഹ വിദൂര സംവേദനം, മണ്ണ് ആരോഗ്യം, ദേശീയ വിള വിശകലനം",
    nav_command_center: "കമാൻഡ് സെന്റർ",
    nav_satellite_srm: "സാറ്റലൈറ്റ് SRM സ്റ്റുഡിയോ",
    nav_soil_precision: "മണ്ണ് ആരോഗ്യം & NPK",
    nav_national_analytics: "ദേശീയ വിള വിശകലനം",
    nav_ai_agronomist: "കൃഷി മിത്ര AI",
    nav_farms: "എന്റെ കൃഷിയിടങ്ങൾ",
    nav_weather: "കാലാവസ്ഥ റഡാർ",
    cmd_welcome: "ദേശീയ കാർഷിക കമാൻഡ് സെന്റർ",
    cmd_sub: "സാറ്റലൈറ്റ് റിമോട്ട് സെൻസിംഗും മണ്ണ് ആരോഗ്യവും സമന്വയിപ്പിച്ച പ്ലാറ്റ്ഫോം",
    cmd_active_farms: "മേൽനോട്ടത്തിലുള്ള കൃഷിഭൂമി",
    cmd_avg_soil_health: "ശരാശരി മണ്ണ് ആരോഗ്യ സൂചിക",
    cmd_satellite_ready: "സാറ്റലൈറ്റ് ന്യൂറൽ എഞ്ചിൻ",
    cmd_national_output: "ദേശീയ ഭക്ഷ്യധാന്യ ഉൽപ്പാദനം",
    cmd_quick_actions: "ദ്രുത പ്രവർത്തനങ്ങൾ",
    cmd_launch_srm: "സാറ്റലൈറ്റ് സൂപ്പർ റെസല്യൂഷൻ പ്രവർത്തിപ്പിക്കുക",
    cmd_test_soil: "മണ്ണിലെ പോഷക ശോഷണം പരിശോധിക്കുക",
    cmd_view_bi: "ദേശീയ വിശകലന ഡാഷ്‌ബോർഡ് തുറക്കുക",
    cmd_ask_ai: "കൃഷി മിത്രയോട് ചോദിക്കുക",
    srm_title: "GeoSR-AI: സാറ്റലൈറ്റ് സൂപ്പർ-റെസല്യൂഷൻ സ്റ്റുഡിയോ",
    srm_subtitle: "Sentinel-2, Landsat സാറ്റലൈറ്റ് ചിത്രങ്ങളുടെ AI സൂപ്പർ-റെസല്യൂഷൻ മാപ്പിംഗ്",
    srm_select_scene: "സാറ്റലൈറ്റ് കാർഷിക ദൃശ്യം തിരഞ്ഞെടുക്കുക",
    srm_or_upload: "അല്ലെങ്കിൽ നിങ്ങളുടെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
    srm_model_select: "ന്യൂറൽ മോഡൽ",
    srm_scale_factor: "സ്കെയിലിംഗ് ഘടകം (4x)",
    srm_run_btn: "സൂപ്പർ-റെസല്യൂഷൻ ആരംഭിക്കുക",
    srm_running: "പ്രക്രിയ പുരോഗമിക്കുന്നു...",
    srm_view_layers: "ദൃശ്യ പാളികൾ",
    srm_layer_rgb: "സൂപ്പർ-റെസല്യൂഷൻ RGB",
    srm_layer_ndvi: "NDVI വിള ആരോഗ്യം",
    srm_layer_nir: "ഫാൾസ്-കളർ NIR",
    srm_layer_unc: "അനിശ്ചിതത്വ ഭൂപടം",
    srm_metrics_header: "ഗുണനിലവാര അളവുകൾ",
    soil_title: "കൃത്യമായ കൃഷിയും 3-സീസൺ മണ്ണിലെ പോഷക ശോഷണവും",
    soil_subtitle: "ഏകവിള പോഷക ശോഷണ പ്രവചനവും വിള ഭ്രമണ പദ്ധതിയും",
    soil_input_card: "മണ്ണ് ആരോഗ്യ കാർഡ് വിവരങ്ങൾ",
    soil_nitrogen: "ലഭ്യമായ നൈട്രജൻ (N)",
    soil_phosphorus: "ലഭ്യമായ ഫോസ്ഫറസ് (P)",
    soil_potassium: "ലഭ്യമായ പൊട്ടാസ്യം (K)",
    soil_ph: "മണ്ണിന്റെ pH",
    soil_oc: "ഓർഗാനിക് കാർബൺ (OC %)",
    soil_calculate: "മണ്ണ് ആരോഗ്യം കണക്കാക്കുക",
    soil_depletion_chart: "3-സീസൺ പോഷക ശോഷണ ഗ്രാഫ്",
    soil_rotation_rec: "ശുപാർശ ചെയ്ത വിള ഭ്രമണം",
    bi_title: "ഭാരത് അഗ്രി അനലിറ്റിക്സ്: ദേശീയ വിള & സാമ്പത്തിക ഡാറ്റ",
    bi_subtitle: "വിള ഉൽപ്പാദനം, കർഷക വരുമാനം, കാലാവസ്ഥ, മണ്ണ് മാട്രിക്സ് ഡാഷ്‌ബോർഡ്",
    bi_tab_crop_prod: "വിള ഉൽപ്പാദനവും ജില്ലകളും",
    bi_tab_farmer_econ: "കർഷക വരുമാനവും ഭൂമിയും",
    bi_tab_climate_impact: "മൺസൂണും കാലാവസ്ഥാ സ്വാധീനവും",
    bi_tab_soil_radar: "മണ്ണ് ആരോഗ്യ റഡാർ മാട്രിക്സ്",
    bi_filter_state: "സംസ്ഥാനം തിരഞ്ഞെടുക്കുക",
    bi_filter_season: "സീസൺ തിരഞ്ഞെടുക്കുക",
    bi_total_prod: "മൊത്തം ഉൽപ്പാദനം",
    bi_cultivated_area: "കൃഷിഭൂമി വിസ്തൃതി",
    bi_avg_yield: "ദേശീയ ശരാശരി വിളവ്",
    bi_avg_income: "കർഷകന്റെ ശരാശരി വരുമാനം",
    chat_title: "കൃഷി മിത്ര — AI കാർഷിക ഉപദേശകൻ",
    chat_subtitle: "ICAR മാർഗ്ഗനിർദ്ദേശങ്ങളെ അടിസ്ഥാനമാക്കിയുള്ള തൽക്ഷണ ശാസ്ത്രീയ ഉപദേശം",
    chat_placeholder: "വിള രോഗങ്ങൾ, വളപ്രയോഗം, അല്ലെങ്കിൽ പദ്ധതികളെക്കുറിച്ച് ചോദിക്കുക...",
    chat_send: "ചോദിക്കുക",
    status_online: "ഓൺലൈൻ",
    status_cpu: "ഉപകരണം: PyTorch റൺടൈം",
    current_farm: "സജീവ കൃഷിയിടം",
    view_details: "വിശദാംശങ്ങൾ കാണുക",
    all_states: "അഖിലേന്ത്യാ (ദേശീയ)"
  },
  or: {
    app_title: "ଏଗ୍ରିସ୍ଫିଅର AI (AgriSphere AI)",
    tagline: "ଭୂ-ସ୍ଥାନିକ ଉପଗ୍ରହ ରିମୋଟ ସେନ୍ସିଂ, ମୃତ୍ତିକା ସ୍ୱାସ୍ଥ୍ୟ ଏବଂ ଜାତୀୟ ଫସଲ ବିଶ୍ଳେଷଣ",
    nav_command_center: "କମାଣ୍ଡ ସେଣ୍ଟର",
    nav_satellite_srm: "ଜିଓଏସଆର ଷ୍ଟୁଡିଓ",
    nav_soil_precision: "ମୃତ୍ତିକା ସ୍ୱାସ୍ଥ୍ୟ ଓ NPK",
    nav_national_analytics: "ଜାତୀୟ ଫସଲ ବିଶ୍ଳେଷଣ",
    nav_ai_agronomist: "କୃଷି ମିତ୍ର AI",
    nav_farms: "ମୋର ଜମି",
    nav_weather: "ପାଣିପାଗ ରାଡାର",
    cmd_welcome: "ଜାତୀୟ କୃଷି କମାଣ୍ଡ ସେଣ୍ଟର",
    cmd_sub: "ଉପଗ୍ରହ ରିମୋଟ ସେନ୍ସିଂ ଏବଂ ମୃତ୍ତିକା ସ୍ୱାସ୍ଥ୍ୟର ଏକୀକୃତ ପ୍ଲାଟଫର୍ମ",
    cmd_active_farms: "ନିରୀକ୍ଷଣ ଅଧୀନ ଚାଷ ଜମି",
    cmd_avg_soil_health: "ହାରାହାରି ମୃତ୍ତିକା ସ୍ୱାସ୍ଥ୍ୟ ସୂଚକାଙ୍କ",
    cmd_satellite_ready: "ଉପଗ୍ରହ ନ୍ୟୁରାଲ ଇଞ୍ଜିନ",
    cmd_national_output: "ଜାତୀୟ ଖାଦ୍ୟଶସ୍ୟ ଉତ୍ପାଦନ",
    cmd_quick_actions: "ଦ୍ରୁତ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ",
    cmd_launch_srm: "ଉପଗ୍ରହ ସୁପର-ରିଜୋଲ୍ୟୁସନ ଚଲାନ୍ତୁ",
    cmd_test_soil: "ମୃତ୍ତିକା ପୋଷକ ତତ୍ତ୍ୱ କ୍ଷୟ ଯାଞ୍ଚ କରନ୍ତୁ",
    cmd_view_bi: "ଜାତୀୟ ବିଶ୍ଳେଷଣ ଡ୍ୟାସବୋର୍ଡ ଖୋଲନ୍ତୁ",
    cmd_ask_ai: "କୃଷି ମିତ୍ରଙ୍କୁ ପଚାରନ୍ତୁ",
    srm_title: "GeoSR-AI: ଉପଗ୍ରହ ସୁପର-ରିଜୋଲ୍ୟୁସନ ଷ୍ଟୁଡିଓ",
    srm_subtitle: "Sentinel-2 ଏବଂ Landsat ଉପଗ୍ରହ ଚିତ୍ରର AI ସୁପର-ରିଜୋଲ୍ୟୁସନ ମ୍ୟାପିଂ",
    srm_select_scene: "ଉପଗ୍ରହ କୃଷି ଦୃଶ୍ୟ ବାଛନ୍ତୁ",
    srm_or_upload: "କିମ୍ବା ନିଜର ଚିତ୍ର ଅପଲୋଡ କରନ୍ତୁ",
    srm_model_select: "ନ୍ୟୁରାଲ ମଡେଲ",
    srm_scale_factor: "ସ୍କେଲିଂ ଗୁଣକ (4x)",
    srm_run_btn: "ସୁପର-ରିଜୋଲ୍ୟୁସନ ଆରମ୍ଭ କରନ୍ତୁ",
    srm_running: "ପ୍ରକ୍ରିୟା ଚାଲିଛି...",
    srm_view_layers: "ଦୃଶ୍ୟ ସ୍ତର",
    srm_layer_rgb: "ସୁପର-ରିଜୋଲ୍ୟୁସନ RGB",
    srm_layer_ndvi: "NDVI ଫସଲ ସ୍ୱାସ୍ଥ୍ୟ",
    srm_layer_nir: "ଫଲ୍ସ-କଲର NIR",
    srm_layer_unc: "ଅନିଶ୍ଚିତତା ମାନଚିତ୍ର",
    srm_metrics_header: "ଗୁଣବତ୍ତା ମେଟ୍ରିକ୍ସ",
    soil_title: "ସଠିକ କୃଷି ଏବଂ ୩-ଋତୁ ମୃତ୍ତିକା ପୋଷକ ତତ୍ତ୍ୱ କ୍ଷୟ",
    soil_subtitle: "ଏକକ ଫସଲ ପୋଷକ କ୍ଷୟ ପୂର୍ବାନୁମାନ ଏବଂ ଫସଲ ପର୍ଯ୍ୟାୟ ଯୋଜନା",
    soil_input_card: "ମୃତ୍ତିକା ସ୍ୱାସ୍ଥ୍ୟ କାର୍ଡ ବିବରଣୀ",
    soil_nitrogen: "ଉପଲବ୍ଧ ନାଇଟ୍ରୋଜେନ (N)",
    soil_phosphorus: "ଉପଲବ୍ଧ ଫସଫରସ (P)",
    soil_potassium: "ଉପଲବ୍ଧ ପୋଟାସିଅମ (K)",
    soil_ph: "ମାଟିର pH",
    soil_oc: "ଜୈବିକ ଅଙ୍ଗାରକ (OC %)",
    soil_calculate: "ମୃତ୍ତିକା ସ୍ୱାସ୍ଥ୍ୟ ଗଣନା କରନ୍ତୁ",
    soil_depletion_chart: "୩-ଋତୁ ପୋଷକ କ୍ଷୟ ଚାର୍ଟ",
    soil_rotation_rec: "ପରାମର୍ଶିତ ଫସଲ ପର୍ଯ୍ୟାୟ",
    bi_title: "ଭାରତ କୃଷି ବିଶ୍ଳେଷଣ: ଜାତୀୟ ଫସଲ ଓ ଆର୍ଥିକ ତଥ୍ୟ",
    bi_subtitle: "ଫସଲ ଉତ୍ପାଦନ, କୃଷକ ଆୟ, ପାଣିପାଗ ଏବଂ ମୃତ୍ତିକା ମ୍ୟାଟ୍ରିକ୍ସ ଡ୍ୟାସବୋର୍ଡ",
    bi_tab_crop_prod: "ଫସଲ ଉତ୍ପାଦନ ଓ ଜିଲ୍ଲା",
    bi_tab_farmer_econ: "କୃଷକ ଆୟ ଓ ଜମି",
    bi_tab_climate_impact: "ମୌସୁମୀ ଓ ଜଳବାୟୁ ପ୍ରଭାବ",
    bi_tab_soil_radar: "ମୃତ୍ତିକା ସ୍ୱାସ୍ଥ୍ୟ ରାଡାର ମ୍ୟାଟ୍ରିକ୍ସ",
    bi_filter_state: "ରାଜ୍ୟ ବାଛନ୍ତୁ",
    bi_filter_season: "ଋତୁ ବାଛନ୍ତୁ",
    bi_total_prod: "ମୋଟ ଉତ୍ପାଦନ",
    bi_cultivated_area: "ଚାଷ ଜମି ଆୟତନ",
    bi_avg_yield: "ଜାତୀୟ ହାରାହାରି ଅମଳ",
    bi_avg_income: "କୃଷକଙ୍କ ହାରାହାରି ଆୟ",
    chat_title: "କୃଷି ମିତ୍ର — AI କୃଷି ପରାମର୍ଶଦାତା",
    chat_subtitle: "ICAR ନିର୍ଦ୍ଦେଶାବଳୀ ଆଧାରରେ ତତକ୍ଷଣାତ ବୈଜ୍ଞାନିକ ପରାମର୍ଶ",
    chat_placeholder: "ଫସଲ ରୋଗ, ସାର ପ୍ରୟୋଗ କିମ୍ବା ସରକାରୀ ଯୋଜନା ବିଷୟରେ ପଚାରନ୍ତୁ...",
    chat_send: "ପଚାରନ୍ତୁ",
    status_online: "ଅନଲାଇନ",
    status_cpu: "ଡିଭାଇସ: PyTorch ରନଟାଇମ",
    current_farm: "ସକ୍ରିୟ ଜମି",
    view_details: "ବିବରଣୀ ଦେଖନ୍ତୁ",
    all_states: "ସମଗ୍ର ଭାରତ (ଜାତୀୟ)"
  },
  as: {
    app_title: "এগ্ৰিস্ফিয়াৰ AI (AgriSphere AI)",
    tagline: "ভূ-স্থানিক উপগ্ৰহ ৰিমোট চেন্সিং, মাটিৰ স্বাস্থ্য আৰু ৰাষ্ট্ৰীয় শস্য বিশ্লেষণ",
    nav_command_center: "কমাণ্ড চেণ্টাৰ",
    nav_satellite_srm: "জিঅ’এছআৰ ষ্টুডিঅ’",
    nav_soil_precision: "মাটিৰ স্বাস্থ্য আৰু NPK",
    nav_national_analytics: "ৰাষ্ট্ৰীয় শস্য বিশ্লেষণ",
    nav_ai_agronomist: "কৃষি মিত্ৰ AI",
    nav_farms: "মোৰ পথাৰ",
    nav_weather: "বতৰ ৰাডাৰ",
    cmd_welcome: "ৰাষ্ট্ৰীয় কৃষি কমাণ্ড চেণ্টাৰ",
    cmd_sub: "উপগ্ৰহ ৰিমোট চেন্সিং আৰু মাটিৰ স্বাস্থ্যৰ একত্ৰিত মঞ্চ",
    cmd_active_farms: "তত্ত্বাৱধানত থকা কৃষিভূমি",
    cmd_avg_soil_health: "গড় মাটিৰ স্বাস্থ্য সূচক",
    cmd_satellite_ready: "উপগ্ৰহ নিউৰেল ইঞ্জিন",
    cmd_national_output: "ৰাষ্ট্ৰীয় খাদ্যশস্য উৎপাদন",
    cmd_quick_actions: "দ্ৰুত পদক্ষেপ",
    cmd_launch_srm: "উপগ্ৰহ ছুপাৰ-ৰিজলিউচন চলাওক",
    cmd_test_soil: "মাটিৰ পুষ্টি হ্ৰাস পৰীক্ষা কৰক",
    cmd_view_bi: "ৰাষ্ট্ৰীয় বিশ্লেষণ ডেশ্বব’ৰ্ড খোলক",
    cmd_ask_ai: "কৃষি মিত্ৰক সোধক",
    srm_title: "GeoSR-AI: উপগ্ৰহ ছুপাৰ-ৰিজলিউচন ষ্টুডিঅ’",
    srm_subtitle: "Sentinel-2 আৰু Landsat উপগ্ৰহ ছবিৰ AI ছুপাৰ-ৰিজলিউচন মেপিং",
    srm_select_scene: "উপগ্ৰহ কৃষি দৃশ্য বাছক",
    srm_or_upload: "বা নিজৰ ছবি আপল’ড কৰক",
    srm_model_select: "নিউৰেল মডেল",
    srm_scale_factor: "স্কেলিং গুণক (4x)",
    srm_run_btn: "ছুপাৰ-ৰিজলিউচন আৰম্ভ কৰক",
    srm_running: "প্ৰক্ৰিয়া চলি আছে...",
    srm_view_layers: "দৃশ্যমান স্তৰ",
    srm_layer_rgb: "ছুপাৰ-ৰিজলিউচন RGB",
    srm_layer_ndvi: "NDVI শস্য স্বাস্থ্য",
    srm_layer_nir: "ফল্ছ-কালাৰ NIR",
    srm_layer_unc: "অনিশ্চয়তা মেপ",
    srm_metrics_header: "গুণগত মান মেট্ৰিক্স",
    soil_title: "সঠিক কৃষি আৰু ৩-ঋতুৰ মাটিৰ পুষ্টি হ্ৰাস",
    soil_subtitle: "একক শস্য পুষ্টি হ্ৰাস পূৰ্বানুমান আৰু শস্য আৱৰ্তন পৰিকল্পনা",
    soil_input_card: "মাটিৰ স্বাস্থ্য কাৰ্ডৰ বিৱৰণ",
    soil_nitrogen: "উপলব্ধ নাইট্ৰ’জেন (N)",
    soil_phosphorus: "উপলব্ধ ফছফৰাছ (P)",
    soil_potassium: "উপলব্ধ পটাছিয়াম (K)",
    soil_ph: "মাটিৰ pH",
    soil_oc: "জৈৱিক কাৰ্বন (OC %)",
    soil_calculate: "মাটিৰ স্বাস্থ্য গণনা কৰক",
    soil_depletion_chart: "৩-ঋতুৰ পুষ্টি হ্ৰাস চাৰ্ট",
    soil_rotation_rec: "পৰামৰ্শিত শস্য আৱৰ্তন",
    bi_title: "ভাৰত কৃষি বিশ্লেষণ: ৰাষ্ট্ৰীয় শস্য আৰু অৰ্থনৈতিক তথ্য",
    bi_subtitle: "শস্য উৎপাদন, কৃষকৰ আয়, বতৰ আৰু মাটি মেট্ৰিক্সৰ ডেশ্বব’ৰ্ড",
    bi_tab_crop_prod: "শস্য উৎপাদন আৰু জিলা",
    bi_tab_farmer_econ: "কৃষকৰ আয় আৰু ভূমি",
    bi_tab_climate_impact: "মৌচুমী আৰু জলবায়ু প্ৰভাৱ",
    bi_tab_soil_radar: "মাটিৰ স্বাস্থ্য ৰাডাৰ মেট্ৰিক্স",
    bi_filter_state: "ৰাজ্য বাছক",
    bi_filter_season: "ঋতু বাছক",
    bi_total_prod: "মুঠ উৎপাদন",
    bi_cultivated_area: "খেতিৰ মাটিৰ কালি",
    bi_avg_yield: "ৰাষ্ট্ৰীয় গড় উৎপাদন",
    bi_avg_income: "কৃষকৰ গড় আয়",
    chat_title: "কৃষি মিত্ৰ — AI কৃষি পৰামৰ্শদাতা",
    chat_subtitle: "ICAR নিৰ্দেশনাৰ আধাৰত তাৎক্ষণিক বৈজ্ঞানিক পৰামৰ্শ",
    chat_placeholder: "শস্যৰ ৰোগ, সাৰৰ মাত্ৰা বা চৰকাৰী আঁচনি সম্পৰ্কে সোধক...",
    chat_send: "সোধক",
    status_online: "অনলাইন",
    status_cpu: "ডিভাইচ: PyTorch ৰাণটাইম",
    current_farm: "সক্ৰিয় পথাৰ",
    view_details: "বিৱৰণ চাওক",
    all_states: "সমগ্ৰ ভাৰত (ৰাষ্ট্ৰীয়)"
  }
};

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिंदी' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ' },
  { code: 'as', name: 'Assamese', native: 'অসমীয়া' },
  { code: 'es', name: 'Spanish', native: 'Español' },
  { code: 'fr', name: 'French', native: 'Français' },
  { code: 'de', name: 'German', native: 'Deutsch' }
];

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => {
    const saved = localStorage.getItem('agri_lang');
    return saved || 'en';
  });
  const [isLiveActive, setIsLiveActive] = useState(true);

  const resetToEnglish = () => {
    localStorage.setItem('agri_lang', 'en');
    setLangState('en');
    document.documentElement.lang = 'en';
    liveTranslatorEngine.stop();
  };

  const setLang = (newLang) => {
    if (newLang === 'en') {
      resetToEnglish();
      return;
    }

    setLangState(newLang);
    localStorage.setItem('agri_lang', newLang);
    document.documentElement.lang = newLang;
    liveTranslatorEngine.start(newLang);
  };

  // Sync translation engine on mount & lang change
  React.useEffect(() => {
    document.documentElement.lang = lang;
    if (lang === 'en') {
      liveTranslatorEngine.stop();
    } else {
      liveTranslatorEngine.start(lang);
    }
  }, [lang]);

  const t = (key) => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en?.[key] || key;
  };

  const translateDynamic = async (text, targetLang = lang) => {
    if (!text || targetLang === 'en') return text;
    const fast = lookupFastTranslation(text, targetLang);
    if (fast) return fast;

    try {
      const res = await api.translate(text, 'en', targetLang);
      return res.translated_text || text;
    } catch {
      return text;
    }
  };

  return (
    <LanguageContext.Provider value={{ 
      lang, 
      setLang, 
      resetToEnglish,
      t, 
      translateDynamic,
      supportedLanguages: SUPPORTED_LANGUAGES,
      isLiveActive,
      setIsLiveActive
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
